config/routes.rb
JulianchamsRails::Application.routes.draw do

  resources :places

  resources :images

  resources :profiles, only: [:show, :edit, :update]

  resources :exhibitions
  

  devise_for :users

  root to: "static_pages#home"

  match '/about' => 'static_pages#about'

  get "static_pages/home" 

  get "static_pages/about"

  get "static_pages/texts"

  get "static_pages/blog"

  get "static_pages/links"

  get "static_pages/work"

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :set_profile

  def home
    @home_page = true
  end

  def work
  end

  def exhibitions
  end

  def about
    user = User.first
  end

  def texts
  end

  def blog
  end

  def links
  end

    private
    def set_profile
      if User.any?
        user=User.first
        @profile = user.profile
      end
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<section>
  <div class="container-fluid">  
    <div class="row-fluid">
      <h1>ABOUT</h1>
      <div class="span5">
        <p><%=@profile.statement%></p>
      
        <%= image_tag ("water1.png") %>
        
        <p><%=@profile.bio%></p>
        <br>

        <h4>Contact</h4>
        <p>Please</p>
        <p><strong>email me </strong><%=@profile.email%></p>
        <p>or</p>
        <p><strong>call me </strong><%=@profile.tel%></p>
			</div>

      <div class="span6">
        <%= image_tag @profile.profile_pic.large.url %>
      </div>

    </div>

    <div class="row-fluid">
      <div class="span5 text-left">
        <!-- AddThis Follow BEGIN -->
        <div class="addthis_toolbox addthis_32x32_style addthis_default_style">
          <a class="addthis_button_facebook_follow" addthis:userid="julianchams"></a>
          <a class="addthis_button_twitter_follow" addthis:userid="julianchams"></a>
          <a class="addthis_button_instagram_follow" addthis:userid="julianchams"></a>
        </div>
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-5123db8437cec11a"></script>
        <!-- AddThis Follow END -->
      </div>
    </div>

        <% if user_signed_in? %>
          <p><%= link_to 'Edit', edit_profile_path(@profile) %>
        <% end %>
        
 	</div>
</section>

app/views/static_pages/blog.html.erb
<section>
  <div class="container-fluid">  
    <div class="row-fluid">
      <div class="span12">
        <h1>HAVEN'T STARTED BLOGGING YET</h1>
      </div>
    </div>
  </div>          
</section>

app/views/static_pages/cv.html.erb
<section>
  <div class="container-fluid">  
    <div class="row-fluid">
      <div class="span3"></div>
          <div class="span6">
            <h1>CV</h1>
            <p>b. 1989, Barranquilla, Colombia<br>
            Lives and works in Brooklyn, NY, USA</p>
            <p><strong>Education</strong></p>
            <p>2008 - 2012</p>
            <p>BFA - Painting, Kansas City Art Institute (KCAI)<br>
            Kansas City, MO, U.S.A</p>
            <p>2011</p>
            <p>Exchange Program - Critical Fine Art Practice, University of Brighton<br>
            Brighton, United Kingdom</p>
            <p><strong>Activity and Honors</strong></p>
            <p>2012-13</p>
            <p>Festival Coordinator and Assistant Curator for Video Art & Experimental Film Festival 
            <br>hosted by Videoart.net, New York City, NY, USA</p>
            <p>2011</p>
            <p>Artist in Residence at St. Peter's Library, University of Brighton, Brighton, UK</p>
            <p>Studio Assistant to James Woodfill, Kansas City, MO, USA</p>
            <p><strong>Collective Exhibitions </strong></p>
            <p>2012</p>
            <p>These Proxies Are for You and They Are True<br>
            Collaborative multimedia installation with Chris Daharsh, Alli Litwicki and Mason Sexton<br>
            City Arts Project, Kansas City, MO, USA</p>
            <p>Annual B.F.A. Exhibition<br>
            H&R Block Artspace, Kansas City, MO, USA</p>
            <p>Store Display<br>
            Nest Luxury, Kansas City, MO, USA</p>
            <p>Construction in Structure<br>
            City Arts Project, Kansas City, MO, USA</p>
            <p>2011</p>
            <p>Brighton University<br>
            Piece permanently installed in St. Peter's Library<br>
            St. Peter's Library, Brighton, UK</p>
            <p>KCAI Accreditation Show<br>
            Dodge Building, Kansas City, MO, USA</p>
            <p>2010</p>
            <p>Fall Be Kind<br>
            Dodge Building, Kansas City, MO<br>
            </p>
          </div>
        <div class="span3"></div>
    </div>
  </div>
</section>

app/views/static_pages/exhibitions.html.erb
<section>
  <div class="container-fluid">  
    <div class="row-fluid">
      <div class="span12">
        <h1>EXHIBITIONS</h1>
        <h5><a href="#">These Proxies Are for You and They Are True</a></h5>
        <p>City Arts Project, Kansas City, MO, USA | 2012<br>
        Collaborative exhibition with Chris Daharsh, Alli Litwicki, and Mason Sexton</p>
        <h5><a href="http://kcai-bfa-2012.org/section/300069_Julian_Chams.html" target="_blank">KCAI BFA Show</a></h5>
        <p>H&R Block Artspace, Kansas City, MO, USA | 2012</p>
        <h5><a href="http://kcaicasestudy.wordpress.com/tag/construction-in-structure/#" target="_blank">Construction in Structure</a></h5>
        <p>City Arts Project, Kansas City, MO, USA | 2012</p>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/links.html.erb
<section>
  <div class="container-fluid">  
    <div class="row-fluid">
      <div class="span12">
        <h1>LINKS</h1>
        
        <p><a href="http://brettginsburg.com" target="_blank">Brett Ginsburg</a></p>
        <p><a href="http://chrisdaharsh.com" target="_blank">Chris Daharsh</a></p>
        <p><a href="http://www.christopherlineberry.info" target="_blank">Christopher Lineberry</a></p>
        <p><a href="http://www.coreyantis.com" target="_blank">Corey Antis</a></p>
        <p><a href="http://www.eduardovelazquez.com" target="_blank">Eduardo Velazquez</a></p>
        <p><a href="http://jameswoodfill.com/blog/" target="_blank">James Woodfill</a></p>
        <p><a href="http://www.madelinegallucci.com" target="_blank">Madeline Gallucci</a></p>
        <p><a href="http://www.sophieroessler.com" target="_blank">Sophie Roessler</a></p>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/store.html.erb
<section>
  <div class="container-fluid">  
    <div class="row-fluid">
      <div class="span12">
        <h1>YOU CAN'T BUY ANYTHING YET I'M SO SORRY</h1>
      </div>
    </div>
  </div>          
</section>

app/views/static_pages/texts.html.erb
<section>
  <div class="container-fluid">  
    <div class="row-fluid">
      <div class="span12">
        <h1>TEXTS</h1>
        <h5><a href="statement.html">Statement</a></h5>
        <p>Artist's statement</p>
        <h5><a href="#">Interview</a></h5>
        <p>Hanna Lodwick and Julian discuss "Internal Synthesis"</p>
        <h5><a href="#">Essay</a></h5>
        <p>Artist writings on "Internal Synthesis"</p>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/work.html.erb
<section>
  <div class="container-fluid">  
    <div class="row-fluid">
      <div class="span12">
        <ul>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_01.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_02.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_03.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_04.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_05.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_06.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_07.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_08.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_09.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_10.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_11.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_12.jpg")%>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <br>
    <div class="row-fluid">
      <div class="span12">
        <ul>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_13.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_14.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_15.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_16.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_17.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_18.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_19.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_20.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_21.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_22.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_23.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_24.jpg")%>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <br>
    <div class="row-fluid">
      <div class="span12">
        <ul>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_25.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_26.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_27.jpg")%>
            </a>
          </li>
          <li class="span00">
            <a href="/static_pages/blah>" class="thumbnail">
              <%= image_tag("wrk_thmb_28.jpg")%>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>          
</section>