config/routes.rb
JulianchamsRails::Application.routes.draw do

  resources :places

  resources :images

  resources :profiles, only: [:show, :edit, :update]

  resources :exhibitions
  

  devise_for :users

  root to: "static_pages#home"

  match '/about' => 'static_pages#about'

  get "static_pages/home" 

  get "static_pages/about"

  get "static_pages/texts"

  get "static_pages/blog"

  get "static_pages/links"

  get "static_pages/work"

end

app/models/exhibition.rb
class Exhibition < ActiveRecord::Base
  attr_accessible :date, :description, :location, :title, :images_attributes
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
  # GET /exhibitions
  # GET /exhibitions.json
  def index
    @exhibitions = Exhibition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exhibitions }
    end
  end

  # GET /exhibitions/1
  # GET /exhibitions/1.json
  def show
    @exhibition = Exhibition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exhibition }
    end
  end

  # GET /exhibitions/new
  # GET /exhibitions/new.json
  def new
    @exhibition = Exhibition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exhibition }
    end
  end

  # GET /exhibitions/1/edit
  def edit
    @exhibition = Exhibition.find(params[:id])
  end

  # POST /exhibitions
  # POST /exhibitions.json
  def create
    @exhibition = Exhibition.new(params[:exhibition])

    respond_to do |format|
      if @exhibition.save
        format.html { redirect_to @exhibition, notice: 'Exhibition was successfully created.' }
        format.json { render json: @exhibition, status: :created, location: @exhibition }
      else
        format.html { render action: "new" }
        format.json { render json: @exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exhibitions/1
  # PUT /exhibitions/1.json
  def update
    @exhibition = Exhibition.find(params[:id])

    respond_to do |format|
      if @exhibition.update_attributes(params[:exhibition])
        format.html { redirect_to @exhibition, notice: 'Exhibition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibitions/1
  # DELETE /exhibitions/1.json
  def destroy
    @exhibition = Exhibition.find(params[:id])
    @exhibition.destroy

    respond_to do |format|
      format.html { redirect_to exhibitions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/views/exhibitions/_form.html.erb
<%= nested_form_for(@exhibition) do |f| %>
  <% if @exhibition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exhibition.errors.count, "error") %> prohibited this exhibition from being saved:</h2>

      <ul>
      <% @exhibition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <fieldset>
    <%= f.fields_for :images do |image|  %>
      <div class="field"
        <%= image.label :image %><br/>
        <%= image.file_field :image %>
        <%= image.hidden_field :image_cache %>
      </div>
      <%= image.link_to_remove "Remove this image" %>
      <br>
    <% end %>
  </fieldset>
  <br>
  <%= f.link_to_add "Add images", :images %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/exhibitions/edit.html.erb
<h1>Editing Exhibition</h1>

<%= render 'form' %>

<%= link_to 'View', @exhibition %> |
<%= link_to 'Back', exhibitions_path %>

app/views/exhibitions/index.html.erb
<div class="container-fluid">  
  <div class="row-fluid">
    <div class="span12">
      <h1>EXHIBITIONS</h1>

      <% @exhibitions.each do |exhibition| %>
        <% if @exhibition.images %>
          <%= image_tag exhibition.images.first.image.small.url %>
        <% end %>
        <h5><%= link_to exhibition.title, exhibition_path(exhibition) %></h5>

        <p><%= exhibition.location %> | <%= exhibition.date %><br>
        <%= exhibition.description %></p>
        <% if user_signed_in? %>
          <br>
          <%= link_to 'View', exhibition %>
           | 
          <%= link_to 'Edit', edit_exhibition_path(exhibition) %>
           | 
          <%= link_to 'Destroy', exhibition, method: :delete, data: { confirm: 'Are you sure?' } %>
           | 
        <% end %>
        <br>
      <% end %>



      <% if user_signed_in? %>
        <%= link_to 'New Exhibition', new_exhibition_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/exhibitions/new.html.erb
<h1>New Exhibition</h1>

<%= render 'form' %>

<%= link_to 'Back', exhibitions_path %>

app/views/exhibitions/show.html.erb
<p id="notice"><%= notice %></p>

  <h1><%= @exhibition.title %></h1>

<% if @exhibition.images %>
	<ul class="bxslider">
	   <% @exhibition.images.each do |i| %>
	   <li><%= image_tag(i.image.url) %></li>
	  <% end %>
	</ul>
<% end %>

  <p> <%= @exhibition.description %> </p>
  <p> <%= @exhibition.location %> | <%= @exhibition.date %> </p>

  <%= link_to 'Edit', edit_exhibition_path(@exhibition) %>
   |
  <%= link_to 'Back', exhibitions_path %>


<%= javascript_include_tag "jquery.bxslider.min.js" %>
<script type="text/javascript"></script>