config/routes.rb
JulianchamsRails::Application.routes.draw do

  resources :places

  resources :images

  resources :profiles, only: [:show, :edit, :update]

  resources :exhibitions
  

  devise_for :users

  root to: "static_pages#home"

  match '/about' => 'static_pages#about'

  get "static_pages/home" 

  get "static_pages/about"

  get "static_pages/texts"

  get "static_pages/blog"

  get "static_pages/links"

  get "static_pages/work"

end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :kind, :title, :image_attributes
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # GET /places
  # GET /places.json
  def index
    @places = Place.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @places }
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/new
  # GET /places/new.json
  def new
    @place = Place.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(params[:place])

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html { render action: "new" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.json
  def update
    @place = Place.find(params[:id])

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= nested_form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>

  <fieldset>
    <%= f.fields_for :images do |image|  %>
      <div class="field"
        <%= image.label :title %><br/>
        <%= image.text_area :title %>
      </div>
      <div class="field"
        <%= image.label :image %><br/>
        <%= image.file_field :image %>
        <%= image.hidden_field :image_cache %>
      </div>
      <%= image.link_to_remove "Remove this image" %>
    <% end %>
  </fieldset>

  <%= f.link_to_add "Add images", :images %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<div class="container-fluid">  
  <div class="row-fluid">
    <div class="span12">
      
      <% if user_signed_in? %>
        <%= link_to 'New Place', new_place_path %>
      <% end %>

      <% @places.each do |place| %>
        <!-- <% if :kind = slideshow then %>
          <% elseif :kind = photo then %>
            <%= image_tag %>
          <% else... %>
        <% end %> -->

        <% if user_signed_in? %>
          <%= link_to 'Edit', edit_place_path(place) %>
          <%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p> <%= @place.title %> </p>
<p> <%= @place.kind %> </p>

<%= link_to 'Edit', edit_place_path(@place) %>
|
<%= link_to 'Back', places_path %>